### PR TITLE
Preparing the release

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by PragTob** [comment]
:wave: 

Thanks for the great library! A release would be really appreciated, I just ran into having the old OAuth versions (0.9) and it's configured Poison dependency without having Poision as a dependency :scream: 

Hence, this would be highly appreciated :tada: 

Here, have a bunny picture:

IMG_20180617_160548

**Comment by yordis** [comment]
😄 vacation at the moment, I will take care of all the packages in 2 days

**Comment by PragTob** [comment]
@yordis please enjoy your vacation :tada: All free time stuff, take care and have a great time!

**Comment by yordis** [comment]
Done 🎉

**Comment by PragTob** [comment]
@yordis thank you very much :tada:

**Pull request merged**
