### PR TITLE
update oauth deps

### PR DESCRIPTION
**Pull request by fajarmf**
- update oauth with 0.9 version

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @fajarmf!  I'll test this today to make sure we're good to go 👍

**Comment by scrogson** [comment]
This PR is relying on an unpublished version of OAuth2 and needs to wait on me completing that work: https://github.com/scrogson/oauth2/pull/70

**Comment by kelostrada** [comment]
also if we update this we will have to update all other strategies - facebook, github, etc, those which rely on oauth too. 
As far as I know, update from `0.8.0` to `0.9.0` shouldn't differ in anything in strategies code so I would opt for updating `oauth2` to `0.8.0` for now. What's your opinion on this guys?

**Comment by scrogson** [comment]
@kelostrada feel free to submit some PRs updating the other strategies to `0.8.0` (if you have the time). I'm pegged at the moment and won't be able to put in any time into this effort.

**Comment by kelostrada** [comment]
I'm working on it, but can you publish master as `0.8.1` to hex? It seems facebook doesn't work with `0.8.0`, but with master it works. If you are not sure about version `0.9.0` for now then I would love at least `0.8.1` to be published, because without that it will be hard to unify all the solutions if some work and others do not... I already prepared them for github, google and facebook. If I find more time I will prepare PRs for other libs too.

**Comment by doomspork** [comment]
@kelostrada / @scrogson — Can this be closed?

**Comment by kelostrada** [comment]
Yeah I think so. I mean if @fajarmf is fine with it, the other PR is just a copy of this with my minor modifications

**Comment by fajarmf** [comment]
Yup it's fine.

**Pull request closed without merging**
